
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, ttk
from data import *
from os import getcwd
from tkinter import messagebox, simpledialog
from datetime import datetime

OUTPUT_PATH = Path(__file__).parent
# ASSETS_PATH = OUTPUT_PATH / Path(r"/home/zifro/git/Tkinter-Designer/build/assets/frame0")
ASSETS_PATH = getcwd() + "/assets/frame"


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("862x480")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 480,
    width = 862,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    862.0,
    74.0,
    fill="#2C41B1",
    outline="")

canvas.create_text(
    57.0,
    19.0,
    anchor="nw",
    text="Dashboard",
    fill="#FFFFFF",
    font=("Inter Bold", 30 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    326.0,
    276.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    753.0,
    120.0,
    image=image_image_2
)

def add_task():
        task_name = simpledialog.askstring("Aggiungi Task", "Inserisci un nuovo task:")
        if task_name:
            category = simpledialog.askstring("Aggiungi Task", "Inserisci la categoria:")
            due_date = simpledialog.askstring("Aggiungi Task", "Inserisci la data (formato: YYYY-MM-DD):")

            if due_date:
                try:
                    due_date = datetime.strptime(due_date, '%Y-%m-%d').date()
                except ValueError:
                    messagebox.showerror("Errore", "Formato data non valido. Utilizza il formato YYYY-MM-DD.")
                    return

            task = {"name": task_name, "category": category, "due_date": due_date}
            # self.tasks.append(task)
            # self.refresh_listbox()

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))

button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=add_task,
    relief="flat"
)

button_2.place(
    x=655.0,
    y=100.0,
    width=196.0,
    height=56.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    753.0,
    254.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    753.0,
    388.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    753.0,
    187.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    753.0,
    321.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    767.0,
    37.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    819.0,
    37.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    30.0,
    37.0,
    image=image_image_9
)

# Creating Table

table = ttk.Treeview(master=window, columns=table_columns, show="headings")

for column in table_columns:
    table.heading(column=column, text=column)
    table.column(column=column, width=70)



# for row_data in table_data:
#     table.insert(parent="", index="end", values=row_data)

style = ttk.Style()
style.theme_use("default")
style.configure("Treeview", background="#917FB3", fieldbackground="#917FB3", foreground="white")
style.configure("Treeview.Heading", background="#917FB3", fieldbackground="#917FB3", foreground="white")
style.map("Treeview", background=[("selected", "#E5BEEC")])

table.place(x=25, y=100, height=260)

window.resizable(False, False)
window.mainloop()
